# https://taskfile.dev

version: "3"

tasks:
  format:
    desc: Format the code (and imports).
    cmds:
      - poetry run isort ./
      - poetry run black ./

  lint:
    desc: Run the linting checks.
    cmds:
      - pre-commit run --all-files

  dev:
    desc: Run dev server
    cmds:
      - poetry run uvicorn app.main:app --reload

  serve:
    desc: Run prod server
    cmds:
      - poetry run uvicorn app.main:app

  setup:
    desc: Configure the development environment.
    cmds:
      - task: setup:pre-commit-hook
      - task: setup:poetry-setup

  setup:pre-commit-hook:
    cmds:
      - pre-commit install
    status:
      - test -f .git/hooks/pre-commit

  setup:poetry-setup:
    cmds:
      - poetry install
    sources:
      - pyproject.toml
