# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: Format the code (and imports).
    cmds:
      - poetry run isort ./
      - poetry run black ./

  lint:
    desc: Run the linting checks.
    cmds:
      - pre-commit run --all-files

  test:
    desc: Run the tests.
    deps:
      - task: "check-mongodb"
    cmds:
      - poetry run pytest -rs

  dev:
    desc: Run dev server
    cmds:
      - poetry run uvicorn app.main:app --reload

  check-mongodb:
    preconditions:
      - sh: command -v nc
        msg: netcat (nc) was not found. Please install it and try again.
      - sh: nc -vz 127.0.0.1 27017 || ! [ -z "$TEST_MONGO_URI" ]
        msg: |
          Mongo server not found, please start a server or start a cluster and set the
          appropriate connection variables

  serve:
    desc: Run prod server
    cmds:
      - poetry run uvicorn app.main:app

  setup:
    desc: Configure the development environment.
    cmds:
      - task: setup:pre-commit-hook
      - task: setup:poetry-setup

  setup:pre-commit-hook:
    cmds:
      - pre-commit install
    status:
      - test -f .git/hooks/pre-commit

  setup:poetry-setup:
    cmds:
      - poetry install
    sources:
      - pyproject.toml
