version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    volumes:
      - ..:/workspace:cached

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/mongodb

volumes:
  mongodb-data:
