name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - corn: "0 8 * * *"

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3.9
        uses: actions/setup-python
        with:
          python-version: 3.9.5
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files
