name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  IMAGE_NAME: chaunceywe/moria-server
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: $IMAGE_NAME
          tags: type=semver,pattern={{version}}

      - name: Login to DockerHub
        if: github.event_name != "pull_request"
        uses: docker/login-action@v1
        with:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

      - name: Build image and publish to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != "pull_request" }}
          tags: ${{ steps.meta.outputs.tags }}
