name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  IMAGE_NAME: chaunceywe/moria-server
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: $IMAGE_NAME
          tags: type=semver,pattern={{version}}

      - name: Login to DockerHub
        run: |
          echo ${{ steps.meta.outputs.tags }}
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

      - name: Build image and publish to registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            latest
            ${{ steps.meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
